import logging
import os

from sqlalchemy.orm import Session

from . import db_models
from .devrev_client import DevRevIssue, create_issue
from .investigator import investigate_suite
from .logging_config import configure_logging
from .models import TestSuiteResult

configure_logging()

logger = logging.getLogger(__name__)


def process_ci_webhook(suite: TestSuiteResult, db: Session) -> dict | None:
    threshold = float(os.getenv("CI_FAILURE_THRESHOLD", "0.2"))

    failure_rate = suite.total_failures / suite.total_tests if suite.total_tests > 0 else 0.0

    if failure_rate == 0 or suite.total_failures == 0:
        return None

    if failure_rate < threshold:
        logger.info(
            "ci_threshold_not_met",
            extra={
                "suite_name": suite.name,
                "failure_rate": failure_rate,
                "threshold": threshold,
            },
        )
        return None

    try:
        # Save suite to Postgres so investigate_suite can query it by ID
        db_suite = db_models.TestSuiteResultORM(
            name=suite.name,
            total_tests=suite.total_tests,
            total_failures=suite.total_failures,
            total_errors=suite.total_errors,
            total_skipped=suite.total_skipped,
            elapsed_time=suite.elapsed_time,
            test_cases=[
                db_models.TestCaseORM(
                    name=tc.name,
                    status=tc.status,
                    failure_message=tc.failure_message,
                )
                for tc in suite.test_cases
            ],
        )
        db.add(db_suite)
        db.commit()
        db.refresh(db_suite)

        report_outer = investigate_suite(db_suite.id, db)
        inner_report = report_outer.get("report", report_outer)

        summary = inner_report.get("summary", "")
        hypotheses = inner_report.get("root_cause_hypotheses", [])
        next_steps = inner_report.get("recommended_next_steps", [])

        priority = "p1" if failure_rate >= 0.5 else "p2"
        title = f"CI Failure: {suite.name} ({suite.total_failures}/{suite.total_tests} tests failed)"

        body_lines = [
            f"## Summary\n{summary}",
            "\n## Root Cause Hypotheses",
        ]
        for h in hypotheses:
            body_lines.append(
                f"- {h.get('hypothesis', '')} (confidence: {h.get('confidence', '')})"
            )
        body_lines.append("\n## Recommended Next Steps")
        for step in next_steps:
            body_lines.append(f"- {step}")
        body_lines.append("\nGenerated by junit-ingest-v2 AI investigator")

        body = "\n".join(body_lines)
        issue = DevRevIssue(title=title, body=body, priority=priority)
        result = create_issue(issue)
    except Exception as exc:
        logger.error("ci_webhook_error", extra={"error": str(exc)})
        raise

    mock_mode = os.getenv("DEVREV_MOCK", "false").lower() == "true"
    logger.info(
        "ci_devrev_issue_dispatched",
        extra={
            "suite_name": suite.name,
            "failure_rate": failure_rate,
            "mock": mock_mode,
        },
    )
    return result
